name: pluginArena
main: fr.geekschool.pluginarena.Main
version: 1.5.0
description: plugin Odysseyus
author: GeekSchool

commands:

  sword:
    description: vous donne l'objet spésifier
    permission: Ava.perm.admin
  frag:
    description: donne tt les objets custom
    permission: Ava.perm.admin
  hotte:
    permission: Ava.perm.admin
  cadeau:
    description: cadeau
  gift:
    permission: Ava.perm.admin
  tete:
    description: command
  clear-hand:
    description: command
  poubelle:
    description: command
  goulag:
    description: command
  event:
    description: command
  presse:
    description: command
  crypto:
    description: command