#Plugin Odysseyus par Pitrouflette - version 5.2.4
#You can not add any lines
#If you want to change any value who is basicly define on {true}, you cant only change the value by {false}
#You have to respect the type of value, for exemple,  if the value is an {int} (ex : Line 49), you have to keep the value as an {int}
#https://ariamamc.com/
#https://github.com/Pitrouflette

##############################################################
#                           Plugin                           #
##############################################################

messages:

  teleportpad:
    teleportpaddeny: "&eErreur : Aucun block de teleportation n'est present !!"

  onjoin:
    title:
      firsttitle: "&c&l&6&lAriamaMC&c&l "
      subtitle: "&ePvP-faction &6&lFarm2Win"
    chat: "&7[&a+&7]"   # + player's pseudo

  commands:
    commands_argument: "&4Veuillez préciser un argument valable : "
    ariama_command: "#4/ariamamc [{reload} || {help} || {items}] "

  help:
    line1: "&3----------&c&l&6&lAriamaMC&r&3----------"
    line2: "&7[&c&l &6&lAriamaMC&c&l Pitrouflette&7]&r &ePlugin &c&l &6&lAriamaMC &c&l&bversion 2.7 &efait par &4Pitrouflette"
    line3: "&7[&c&l &6&lAriamaMC&c&l Pitrouflette&7]&r &eLe plugin comprends le système &bd'armure en §bcrystals&e, de &2linked chest &eet de &5téléport-pad !"
    line4: "&3----------&c&l&6&lAriamaMC&r&3----------"

  reload:
    succes: "&7[&c&l &6&lAriamamcm&c&l Pitrouflette&7]&r &2Plugin reloaded succesfully"
    fail: "&7[&c&l &6&lAriamamcm&c&l Pitrouflette&7]&r &4Plugin reload failure"

teleportpad:
  status:
    allow: true
    deny: "&eCette options est bloquee"

linkedchest:                      #Some bug like duplication bug can be find while using this fonctionality, this is why it's basicly define on {false}
  status:
    allow: false
    deny: "&eCette options est bloquee"

  ##############################################################
  #                         InfiniteItem                       #
  ##############################################################

items:

  placeholder:            #use this to introduce a varible in your item's lore/name
    player: "<player>"

  sword:
    name: "YourNameitem"
    lore:
      - "Your item's Lore"
      - "Your item's Lore"
      - "Your item's Lore"
      - "Your item's Lore"

  bow:
    name: "YourNameitem"
    lore:
      - "Your item's Lore"
      - "Your item's Lore"
      - "Your item's Lore"
      - "Your item's Lore"

  rod:
    name: "YourNameitem"
    lore:
      - "Your item's Lore"
      - "Your item's Lore"
      - "Your item's Lore"
      - "Your item's Lore"



  ##############################################################
  #                         FactionClass                       #
  ##############################################################

factions:
  messages:
    faction-not-exist: "&4Ce joueur n'a pas de factions"
  ##############################################################
  #                           Securité                        #
  ##############################################################

security:

  op-commands:
    - "/op"

  ##############################################################
  #                           Punish                           #
  ##############################################################

  punish-hack-try-op: "kick <player> tentative de prise de controle"

  punish-hack-try-gm: "kick <player> tentative de triche ou de Hack"

  ##############################################################
  #                           Messages                         #
  ##############################################################

  messages:
    cant-say-that: "&4Vous ne pouvez pas dire ce mot, il est prohibé"
    command-blocked-message: "&4Vous ne pouvez pas utiliser cette command, elle est prohibé"
    oped-blocked-message: "&4Vous ne pouvez pas avoir le mode de jeu creative !!"
    gm-blocked: "&4Vous ne pouvez pas admettre ce mode de jeu a qui que ce sois, vous allez être puni !!"

  ##############################################################
  #                           Whitlist                         #
  ##############################################################

  whitlist-op:
    - pitrouflette
    - ChilDish
    - ChilDishSkenD0
    - pitroufletteuhh

  whitlist-gm:
    - pitrouflette
    - ChilDish
    - ChilDishSkenD0
    - pitroufletteuhh

  whitlist-commands:
    - pitrouflette
    - ChilDish
    - ChilDishSkenD0
    - pitroufletteuhh

  whitlist-messages:
    - pitrouflette
    - ChilDish
    - ChilDishSkenD0
    - pitroufletteuhh

  ##############################################################
  #                          Permission                        #
  ##############################################################

  permission-bypass: "security.bypass"

  ##############################################################
  #                      BlockedThings                         #
  ##############################################################

  blocked-commands:
    - op
    - gms
    - gmsp
    - gmc
    - /pl
    - /plugins
    - /?
    - /bukkit:?
    - /bukkit:plugins
    - /bukkit:pl
    - /bukkit:help
    - /ver
    - /version
    - /bukkit:version
    - /bukkit:ver
    - /bukkit:reload
    - /bukkit:rl
    - /bukkit:timings
  blocked-words:
    - fdp
    - pd
    - connard
    - ez
    - ntm
    - ntr
    - tg
    - gueule
    - bouffon
    - enculer
    - enculé
    - putain
    - putin
    - con
    - conne
    - nul
    - ez
    - merde
    - connard
    - connasse
    - connace
    - easy
    - sdf
    - clochard
    - clochar
    - zoulette
    - negro
    - minemen
    - mmc
    - hadaria
    - nigga
    - suce
    - bite
    - chatte
    - cul
    - zgeg
    - zezette
    - zizi
    - pticon
    - enfoiré
    - enfoirer
    - dtc
    - tdc
    - trdc
    - endouille
    - imbécile
    - chien
    - chiennasse
    - pétasse
    - pute
    - pd
    - gay
    - pédale
    - branleur
    - branleuse
    - bougnoule
    - bouffonne
    - clc
    - casse-couilles
    - crétin
    - djihadiste
    - hitler
    - Adolf
    - Staline
    - Lenine
    - Juif
    - enflures
    - enflure
    - emmerdeur
    - chleuh
    - chnok
    - chieur
    - chintoc
    - couffar
    - kouffar
    - chrétien
    - lgbt
    - batard
    - ntp
    - nts
    - ntf