main: fr.pitrouflette.ariamamc.Main
name: AriamamMC
author: pitrouflette
version: 1.2.3

commands:
  armureupunbreaking:
    description: augmente la durabilite de votre pièce d'armure en Crystal
  armureupprotection:
    description: augmente la protection de votre pièce d'armure en Crystal
  armurerepair:
    description: Répare votre armure en crystal
  ariamamc:
    description: util plugin
    permission: perm.ariamamc.admin
  event:
    description: the event command